name: Invoke Export Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
      applications:
        description: 'Comma-separated applications to export'
        required: false

jobs:
  call-export:
    uses: Iberdrola/github-actions-auth0-deploy/.github/workflows/dev-config-tagging-v2.yaml@feature/auth0-ci
    with:
      tag: ${{ github.event.inputs.tag }}
      applications: ${{ github.event.inputs.applications }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      AUTH0_CLIENT_ID: "pBJkuNioAfmXs0NBim8JPjVYP6p9Nj58"
      AUTH0_CLIENT_SECRET: "vn02uMgaVQ-r5cZUCt7HIscINtNPJCkdaHkFPX12fcMnUwilBo85gy5bfqI9MXmJ"
      AUTH0_DOMAIN: "dev-cicd-poc-1.eu.auth0.com"
      AUTH0_AUDIENCE: "https://dev-cicd-poc-1.eu.auth0.com/api/v2/"
